myproject/core/urls.py
from django.urls import path
from myproject.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.Index.as_view(), name='index'),
    path('add/', v.MyCreate.as_view(), name='add'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField('título', max_length=100)

    class Meta:
        ordering = ('title',)
        verbose_name = 'livro'
        verbose_name_plural = 'livros'

    def __str__(self):
        return self.title


class Movie(models.Model):
    title = models.CharField('título', max_length=100)

    class Meta:
        ordering = ('title',)
        verbose_name = 'livro'
        verbose_name_plural = 'livros'

    def __str__(self):
        return self.title

myproject/core/forms.py
from django import forms
from .models import Book, Movie


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title',)


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = ('title',)

myproject/core/views.py
from django.forms import forms
from django.views.generic import TemplateView, CreateView
from django.views.generic.edit import FormMixin

from .forms import BookForm, MovieForm


class Index(TemplateView):
    template_name = 'index.html'


class MultiFormCreateView(CreateView):
    form_classes = None
    query_param = 'form'

    def get_form(self, form_class=None):
        if not form_class:
            param = self.request.GET.get(self.query_param)
            # Safety fallback to empty form.
            form_class = self.form_classes.get(param, forms.Form)
        return super().get_form(form_class)

    def get_context_data(self, **kwargs):
        for name, form in self.form_classes.items():
            if name in kwargs:
                continue

            kwargs[name] = self.get_form(form)
        return super(FormMixin, self).get_context_data(**kwargs)


class MyCreate(MultiFormCreateView):
    form_classes = {'bookForm': BookForm, 'movieForm': MovieForm}
    template_name = 'form.html'
    success_url = '/add/'

myproject/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>Django Two Forms</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

  <style>
    body {
      margin-top: 60px;
    }
  </style>

  {% block css %}{% endblock css %}

  </body>
</head>
<body>


  <div class="container">
    {% block content %}{% endblock content %}
  </div>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  {% block js %}{% endblock js %}

</body>
</html>

myproject/core/templates/form.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
  <div class="row">

    <div class="col-md-6">

      <form role="form" method="post" action=".?form=bookForm">
          {% csrf_token %}
        <div class="form-group">
            {{ bookForm.title }}
        </div>
        <button type="submit" class="btn btn-primary">
          Salvar
        </button>
      </form>

    </div>

    <div class="col-md-6">

      <form role="form" method="post" action=".?form=movieForm">
          {% csrf_token %}
        <div class="form-group">
          {{ movieForm.title }}
        </div>
        <button type="submit" class="btn btn-primary">
          Salvar
        </button>
      </form>

    </div>

  </div>
</div>

{% endblock content %}

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <h3>Exemplo do uso de dois formulários na mesma classe (<a href="http://ccbv.co.uk/" target="_blank">CBV</a>).</h3>
    <p>
      <a href="{% url 'core:add' %}">Formulário</a>
    </p>
  </div>
</div>

{% endblock content %}